ERROR - 2022-12-31 06:02:40 --> mysqli_sql_exception: Column 'id_usuario' cannot be null in C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\pos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\pos\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pos\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pos\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\pos\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\pos\app\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\pos\system\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
#10 C:\xampp\htdocs\pos\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#11 C:\xampp\htdocs\pos\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-12-31 06:02:40 --> Column 'id_usuario' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 06:02:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 06:02:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 06:02:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (:id_usuario:, :evento:, :ip:, :detalles:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 06:42:30 --> Undefined variable: idRol
in APPPATH\Controllers\Productos.php on line 40.
 1 APPPATH\Controllers\Productos.php(40): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: idRol', 'APPPATH\\Controllers\\Productos.php', 40, [...])
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Productos->index()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 08:29:56 --> Undefined index: nombre_corto
in APPPATH\Views\cajas\cajas.php on line 31.
 1 APPPATH\Views\cajas\cajas.php(31): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: nombre_corto', 'APPPATH\\Views\\cajas\\cajas.php', 31, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\cajas\\cajas.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('cajas/cajas', [], true)
 5 APPPATH\Controllers\Cajas.php(41): view('cajas/cajas', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 08:45:19 --> Undefined index: nombre_caja
in APPPATH\Views\cajas\editar.php on line 19.
 1 APPPATH\Views\cajas\editar.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: nombre_caja', 'APPPATH\\Views\\cajas\\editar.php', 19, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\cajas\\editar.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('cajas/editar', [], true)
 5 APPPATH\Controllers\Cajas.php(98): view('cajas/editar', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->editar('1')
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 08:47:01 --> Undefined index: nombre_caja
in APPPATH\Views\cajas\editar.php on line 19.
 1 APPPATH\Views\cajas\editar.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: nombre_caja', 'APPPATH\\Views\\cajas\\editar.php', 19, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\cajas\\editar.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('cajas/editar', [], true)
 5 APPPATH\Controllers\Cajas.php(98): view('cajas/editar', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->editar('1')
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 08:47:06 --> Undefined index: nombre_caja
in APPPATH\Views\cajas\editar.php on line 19.
 1 APPPATH\Views\cajas\editar.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: nombre_caja', 'APPPATH\\Views\\cajas\\editar.php', 19, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\cajas\\editar.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('cajas/editar', [], true)
 5 APPPATH\Controllers\Cajas.php(98): view('cajas/editar', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->editar('1')
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 09:50:15 --> Undefined property: App\Controllers\Cajas::$session
in APPPATH\Controllers\Cajas.php on line 142.
 1 APPPATH\Controllers\Cajas.php(142): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: App\\Controllers\\Cajas::$session', 'APPPATH\\Controllers\\Cajas.php', 142, [...])
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->nuevo_arqueo()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 09:51:02 --> Undefined variable: arqueos
in APPPATH\Controllers\Cajas.php on line 143.
 1 APPPATH\Controllers\Cajas.php(143): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: arqueos', 'APPPATH\\Controllers\\Cajas.php', 143, [...])
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->nuevo_arqueo()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 09:51:29 --> Invalid file: cajas/nuevo_arqueo.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('cajas/nuevo_arqueo.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('cajas/nuevo_arqueo', [], true)
 3 APPPATH\Controllers\Cajas.php(145): view('cajas/nuevo_arqueo', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->nuevo_arqueo()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 09:59:06 --> Undefined variable: caja
in APPPATH\Views\cajas\nuevo_arqueo.php on line 19.
 1 APPPATH\Views\cajas\nuevo_arqueo.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: caja', 'APPPATH\\Views\\cajas\\nuevo_arqueo.php', 19, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\cajas\\nuevo_arqueo.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('cajas/nuevo_arqueo', [], true)
 5 APPPATH\Controllers\Cajas.php(145): view('cajas/nuevo_arqueo', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Cajas->nuevo_arqueo()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cajas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-31 10:36:37 --> mysqli_sql_exception: Unknown column 'fecha_modifica' in 'field list' in C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cajas` ...', 0)
#1 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cajas` ...')
#2 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cajas` ...')
#3 C:\xampp\htdocs\pos\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cajas` ...', Array, false)
#4 C:\xampp\htdocs\pos\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\pos\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\pos\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\pos\app\Controllers\Ventas.php(75): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\pos\system\CodeIgniter.php(927): App\Controllers\Ventas->guarda()
#9 C:\xampp\htdocs\pos\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ventas))
#10 C:\xampp\htdocs\pos\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-31 10:36:37 --> Unknown column 'fecha_modifica' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `cajas` SET `folio` = 6, `fecha_modifica` = \'2022-12-31 10:36:37\'
WHERE `cajas`.`id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `cajas` SET `folio` = 6, `fecha_modifica` = \'2022-12-31 10:36:37\'
WHERE `cajas`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `cajas` SET `folio` = 6, `fecha_modifica` = \'2022-12-31 10:36:37\'
WHERE `cajas`.`id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `cajas` SET `folio` = :folio:, `fecha_modifica` = :fecha_modifica:
WHERE `cajas`.`id` IN :cajas.id:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Ventas.php(75): CodeIgniter\Model->update('1', [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Ventas->guarda()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ventas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 13:28:36 --> Class 'XSLTProcessor' not found
in APPPATH\Libraries\cfdi_sat\satxmlsv33.php on line 184.
 1 APPPATH\Libraries\cfdi_sat\satxmlsv33.php(28): GeneraXML->satxmlsv33_genera_cadena_original('APPPATH\\Libraries\\cfdi_sat')
 2 APPPATH\Controllers\Factura.php(64): GeneraXML->satxmlsv33([...], 'ROOTPATH\\public', 'APPPATH\\Libraries\\cfdi_sat', 'ROOTPATH\\public')
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Factura->facturar('31')
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Factura))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 17:23:42 --> Undefined property: App\Controllers\Factura::$ventas
in APPPATH\Controllers\Factura.php on line 26.
 1 APPPATH\Controllers\Factura.php(26): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: App\\Controllers\\Factura::$ventas', 'APPPATH\\Controllers\\Factura.php', 26, [...])
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Factura->facturar('31')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Factura))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-31 18:33:11 --> mysqli_sql_exception: Column 'id_usuario' cannot be null in C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\pos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\pos\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pos\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pos\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\pos\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\pos\app\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\pos\system\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
#10 C:\xampp\htdocs\pos\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#11 C:\xampp\htdocs\pos\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-12-31 18:33:11 --> Column 'id_usuario' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (:id_usuario:, :evento:, :ip:, :detalles:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-31 18:33:16 --> mysqli_sql_exception: Column 'id_usuario' cannot be null in C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\pos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\pos\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pos\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pos\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\pos\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\pos\app\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\pos\system\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
#10 C:\xampp\htdocs\pos\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#11 C:\xampp\htdocs\pos\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-12-31 18:33:16 --> Column 'id_usuario' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (:id_usuario:, :evento:, :ip:, :detalles:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-31 18:33:29 --> mysqli_sql_exception: Column 'id_usuario' cannot be null in C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\pos\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\pos\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\pos\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\pos\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\pos\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\pos\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\pos\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\pos\app\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\pos\system\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
#10 C:\xampp\htdocs\pos\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#11 C:\xampp\htdocs\pos\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pos\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-12-31 18:33:29 --> Column 'id_usuario' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:29\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:29\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (NULL, \'Cierre de sesión\', \'::1\', \'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36\', \'2022-12-31 18:33:29\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logs` (`id_usuario`, `evento`, `ip`, `detalles`, `fecha`) VALUES (:id_usuario:, :evento:, :ip:, :detalles:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Usuarios.php(252): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Usuarios->logout()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 19:51:49 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 867.
 1 SYSTEMPATH\BaseModel.php(867): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Factura.php(98): CodeIgniter\Model->update('33', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Factura->facturar('33')
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Factura))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-31 19:55:43 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 867.
 1 SYSTEMPATH\BaseModel.php(867): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\Factura.php(98): CodeIgniter\Model->update('33', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Factura->facturar('33')
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Factura))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
